package antiban.api.game.login_handler.enums;

import java.awt.*;

public enum LoginState {

    WELCOME(new Point(310, 241), new Color(255, 255, 0), null),
    WORLD_SELECT(new Point(645, 11), new Color(255, 255, 255), null),
    INCORRECT_PASSWORD(new Point(219, 234), new Color(255, 255, 0), null),
    LOGIN_FORM(new Point(362, 213), new Color(255, 255, 0), "Please enter your"),
    LOADING(new Point(310, 206), new Color(255, 255, 0), "Connecting to server..."),
    MEMBERS_ONLY(null, null, "You need a members account to login to this world. Please subscribe, or use a different world."),
    BANNED(null, null, "Your account has been disabled. Please check your message-centre for details."),
    AUTHENTICATOR(null, null, "Enter the 6-digit code generated by your authenticator app."),
    LOCKED(null, null, "Account locked as we suspect it has been stolen. Press 'recover a locked account' on front page."),
    BILLING(null, null, "Your attempt to log into your account was unsuccessful.  Don't worry, you can sort this out by visiting the billing system."),
    DISPLAY_NAME(null, null, "Please choose yourself a display name via the website before logging in.");

    public final Point POINT;
    public final Color COLOR;
    public final String STATUS;

    LoginState(Point point, Color color, String status) {
        this.POINT = point;
        this.COLOR = color;
        this.STATUS = status;
    }

    public Point getPoint() {
        return POINT;
    }

    public Color getColor() {
        return COLOR;
    }

    public String getStatus() {
        return STATUS;
    }

}
